### ISSUE TITLE
Observation - (Simple & Atomic) Imaging Observation: code - terminology support

### ISSUE THREAD

**Issue by davidmckillop** [AuDigitalHealth/ci-fhir-r4#54] opened 2020-05-05 21:19 UTC
# Prerequisites
- [x] I have searched [open](https://github.com/ci-fhir-r4/Issues/issues) and [closed](https://github.com/ci-fhir-r4/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested or reported
- [x] I have written a descriptive issue title

# The issue
## Change description
It is unclear if the slice from HL7 AU Diagnostic Observation coding:snomedImagingProcedure is sufficient for supporting electronic exchange of diagnostic imaging observations in Australia.

Feedback from stakeholders should be sought on the need for additional terminologies in this sector, e.g. http://hl7.org/fhir/uv/ips/ValueSet/imaging-observations-uv-ips. It is expected that this would be progressed via a HL7 AU Working Group and any additional support be included in the HL7 AU Base Implementation Guide in AU Diagnostic Observation.

## Mockups 
If applicable, add screenshots or mockups to help explain the issue / feature. 

## Additional context
Add any other context or links about the issue or feature here, e.g. replicate this page over here in this context.

**Comment by dtr-agency** [comment] 2020-05-05 21:30
This is a duplicate of 53.

**Closed by dtr-agency** 2020-05-05 21:30 UTC
Labels: closed/duplicate
